matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
  fast_finish: true

addons:
  artifacts:
    paths:
      - $(ls powershell*{deb,pkg,AppImage,gz} | tr "\n" ":")
      - TestResultsSudo.xml
      - TestResultsNoSudo.xml

sudo: required
services: [docker]

install:
  - docker info
  - bash <(curl -s https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/installpsh-debian.sh)

script:
  - pwsh -File ./build.ps1 -build -name ubuntu14.04
  - pwsh -File ./build.ps1 -build -name ubuntu16.04
  - pwsh -File ./build.ps1 -build -name centos7
