name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

pr:
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - .vsts-ci/releasebuild.yml
    - .vsts-ci/ltsReleaseStage.yml
    - .vsts-ci/previewReleaseStage.yml
    - .vsts-ci/stableReleaseStage.yml
    - assets/matrix.json
    - README.md

resources:
- repo: self
  clean: true

variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1

stages:
  - template: .vsts-ci/stage.yml
    parameters:
      channel: stable
  - template: .vsts-ci/stage.yml
    parameters:
      channel: preview
  - template: .vsts-ci/stage.yml
    parameters:
      channel: lts

  - stage: CheckForDuplicateTags
    displayName: Check for duplicate tags
    dependsOn: []
    jobs:
    - job: CheckForDuplicateTags
      pool:
        vmImage: ubuntu-latest
      displayName: Check For Duplicate Tags
      steps:
      - pwsh: Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhss"))"
        displayName: Set Build Name for Non-PR
        condition: ne(variables['Build.Reason'], 'PullRequest')
      - pwsh: |
          try {
            ./build.ps1 -CheckForDuplicateTags -Channel stable, preview, lts
          } catch {
            Get-Error
            throw
          }
        displayName: Check for Duplicate Tags
        condition: succeededOrFailed()

  - stage: Secret_Scan
    displayName: Secret Scan
    dependsOn: []
    jobs:
    - job: Secret_Scan
      pool:
        vmImage: windows-latest
      displayName: Secret Scan

      steps:
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
        displayName: 'Scan for secrets'
        inputs:
          debugMode: false
          toolMajorVersion: V2

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
        displayName: 'Publish Secret Scan Logs to Build Artifacts'
        continueOnError: true

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
        displayName: 'Check for Failures'
        inputs:
          CredScan: true
          ToolLogsNotFoundAction: Error
