resources:
- repo: self
  clean: true

variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1

stages:
  - template: communityReleaseStage.yml
    parameters:
      channel: community-stable
      jobName: community_stable
