variables:
  - group: mcrint
  
parameters:
  - name: publicSource
    value: no
    displayname: no if the source requires login, yes if the source does not.

jobs:
- job: Mirror
  pool:
    vmImage: vs2017-win2016

  strategy:
    matrix:
      servercore: 
        sourceImage: private/windows/servercore:ltsc2022
        targetImage: windows/servercore:ltsc2022
      nanoserver: 
        sourceImage: private/windows/nanoserver:ltsc2022
        targetImage: windows/nanoserver:ltsc2022

  displayName: Mirror Image $(targetImage)
  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: Mirror $(targetImage) - with login
    condition: and(succeeded(), eq('${{ parameters.publicSource', 'no'))
    inputs:
      connectedServiceNameARM: c58d97a0-15dd-4781-b8b9-c8a0c2fdcdd9
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: >-
        az acr import --name $(targetusername) `
          --source $(mcrinthostname)/$(sourceImage) `
          --image $(targetImage) `
          --username $(mcrintusername) `
          --password $(mcrintsecret)
  - task: AzureCLI@2
    displayName: Mirror $(targetImage) - without login
    condition: and(succeeded(), ne('${{ parameters.publicSource', 'no'))
    inputs:
      connectedServiceNameARM: c58d97a0-15dd-4781-b8b9-c8a0c2fdcdd9
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: >-
        az acr import --name $(targetusername) `
          --source $(mcrinthostname)/$(sourceImage) `
          --image $(targetImage)
         
