parameters:
  pool: 'Hosted Ubuntu 1604'
  channel: 'stable'
  nameSuffix: 'none'
  ACR: 'no'

jobs:
- job: ${{ parameters.channel }}${{ parameters.nameSuffix }}
  variables:
    dockerImage: 'powershell'
    ImageName: ${{ parameters.imagename }}
    Channel: ${{ parameters.channel }}
    ACR: ${{ parameters.ACR }}

  pool: ${{ parameters.pool }}
  timeoutInMinutes: 135

  displayName: ${{ parameters.channel }}

  condition: eq(variables['${{ parameters.channel }}'], 'true')

  steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=ACR_NAME;]$env:ACR_NAME_VAR"
    displayName: 'Enable ACR'
    condition: ne(variables['ARC'], 'no')

  - powershell: 'Get-ChildItem env:' 
    displayName: 'Capture Environment'

  - powershell: 'docker login $(dockerHost) -u $(dockerUserName) -p $(dockerKey)' 
    displayName: 'docker login'

  - powershell: ' az login --service-principal -u $(az_url) -p $(az_key) --tenant $(az_name)' 
    displayName: 'az acr login'
    condition: and(succeeded(),ne(variables['ARC'], 'no'))

  - powershell: 'Install-module pester -Scope CurrentUser -Force -SkipPublisherCheck' 
    displayName: 'Install Pester'

  - powershell: './build.ps1 -Build -ImageName $(dockerHost)/$(dockerNamespace)/$(dockerImage) -All -Channel $(channel) -Push' 
    displayName: 'Build All $(Channel)'
    condition: eq(variables['stable'], 'true')

  - powershell: 'docker logout $(dockerHost)' 
    displayName: 'docker logout'
    condition: always()

  - powershell: 'az logout' 
    displayName: 'az logout'
    condition: ne(variables['ARC'], 'no')
