parameters:
  pool: 'Hosted Ubuntu 1604'
  channel: 'stable'
  jobName: 'none'
  ACR: 'no'

jobs:
- job: ${{ parameters.jobName }}
  variables:
    dockerImage: 'powershell'
    ImageName: ${{ parameters.imagename }}
    Channel: ${{ parameters.channel }}
    ACR: ${{ parameters.ACR }}

  pool: ${{ parameters.pool }}
  timeoutInMinutes: 135

  displayName: ${{ parameters.jobName }}

  steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=ACR_NAME;]$env:ACR_NAME_VAR"
    displayName: 'Enable ACR'
    condition: ne(variables['ACR'], 'no')

  - powershell: 'Get-ChildItem env:' 
    displayName: 'Capture Environment'

  - powershell: 'docker login $(dockerHost) -u $(dockerUserName) -p $(dockerKey)' 
    displayName: 'docker login'

  - powershell: ' az login --service-principal -u $(az_url) -p $(az_key) --tenant $(az_name)' 
    displayName: 'az acr login'
    condition: and(succeeded(),ne(variables['ARC'], 'no'))

  - powershell: 'Install-module pester -Scope CurrentUser -Force -SkipPublisherCheck' 
    displayName: 'Install Pester'

  - powershell: |
      $extraParams = @{}
      if(!$env:ACR)
      {
        Write-Host 'Not in ACR, will push...'
        $extraParams.Add('Push',$true)
      }
      if($env:$(Channel) -eq 'true')
      {
        ./build.ps1 -Build -ImageName $(dockerHost)/$(dockerNamespace)/$(dockerImage) -All -Channel $(channel) @extraParams
      }
      else
      {
        Write-Host 'Current channel disabled, skipping ...'
      }
    displayName: 'Build All $(Channel)'

  - powershell: 'docker logout $(dockerHost)' 
    displayName: 'docker logout'
    condition: always()

  - powershell: 'az logout' 
    displayName: 'az logout'
    condition: ne(variables['ARC'], 'no')
