resources:
- repo: self
  clean: true
jobs:

- template: releasePhase.yml
  parameters:
    channel: STABLE
    jobName: stableLinux
    pool: Hosted Ubuntu 1604
    ACR: no

- template: releasePhase.yml
  parameters:
    channel: PREVIEW
    jobName: previewLinux
    pool: Hosted Ubuntu 1604
    ACR: no

- template: releasePhase.yml
  parameters:
    channel: STABLE
    jobName: stableWindows
    pool: Hosted VS2017
    ACR: yes

- template: releasePhase.yml
  parameters:
    channel: PREVIEW
    jobName: previewWindows
    pool: Hosted VS2017
    ACR: yes

- job: ManifestPhase
  displayName: Create Manifest Lists

  dependsOn: 
   - stableLinux
   - previewLinux
   - stableWindows
   - previewWindows
  condition: succeeded()
  pool:
    name: PowerShell
    timeoutInMinutes: 30

  steps:
  - powershell: |  
       $dockerConfigFolder = "$env:userprofile/.docker"
       if(!(Test-Path $dockerConfigFolder)){ $null = new-item -Type Directory -Path $dockerConfigFolder}
       $dockerCliConfig = "$env:userprofile/.docker/config.json"
       $dockerCliBackup = "$env:userprofile/.docker/config-backup.json"
       if(Test-Path $dockerCliConfig) { copy-item $dockerCliConfig $dockerCliBackup -force}
       @{experimental='enabled'}|ConvertTo-Json | Out-File -Encoding ascii -FilePath $dockerCliConfig
        
    displayName: 'enable docker cli experimental features'

  - powershell: 'docker login $(dockerHost) -u $(dockerUserName) -p $(dockerKey)' 
    displayName: 'docker login'

  - powershell: |
      ./createAllManifests.ps1 -Registry '$(dockerHost)/$(dockerNamespace)'
    displayName: 'Create Manifest Lists'

  - powershell: 'docker logout $(dockerHost)' 
    displayName: 'docker logout'
    condition: always()
