parameters:
  - name: channel
    default: 'preview'
  - name: vmImage
    default: PSMMSUbuntu20.04-Secure
  - name: acr
    default: 'All'
  - name: useacr
    default: 'false'
  - name: osFilter
    default: 'All'

stages:
  - stage: GenerateYaml_${{ parameters.channel }}
    dependsOn: ['GenerateFullTag']
    displayName: Build ${{ parameters.channel }}
    jobs:
    - job: GenerateYaml_${{ parameters.channel }}
      pool:
        name: PowerShell1ES
        demands:
          - ImageOverride -equals ${{ parameters.vmImage }}

      displayName: Generate Matrix YAML ${{ parameters.channel }}
      steps:
      - pwsh: |
          ./build.ps1 -GenerateMatrixJson -Channel ${{ parameters.channel }} -Verbose -Acr ${{ parameters.acr }} -OsFilter ${{ parameters.osFilter }}
        displayName: Generate Matrix YAML
        condition: succeededOrFailed()
        name: matrix
      - pwsh: |
          dir env:matrix_* | out-string -Width 1000
        displayName: Capture Matrix YAML
        condition: succeededOrFailed()
    - template: releasePhase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_amd64']
        dependsOn:
          - GenerateYaml_${{ parameters.channel }}
        jobName: Build_Linux_x64

    - template: releasePhase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_arm64']
        dependsOn:
          - GenerateYaml_${{ parameters.channel }}
        jobName: Build_Linux_arm64
        pool: PS-mscodehub-ARM
        vmImage: PSMMSUbuntu20.04-ARM64-secure

    - template: releasePhase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_arm32']
        dependsOn:
          - GenerateYaml_${{ parameters.channel }}
        jobName: Build_Linux_arm32
        pool: PS-mscodehub-ARM
        vmImage: PSMMSUbuntu20.04-ARM64-secure
        
    - template: releasePhase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_windows_amd64']
        dependsOn:
          - GenerateYaml_${{ parameters.channel }}
        jobName: Build_Win_x64
        vmImage: PSMMS2019-Secure
        ACR: yes
        maxParallel: 3
