resources:
- repo: self
  clean: true
jobs:

- template: releasePhase.yml
  parameters:
    channel: stable

- template: releasePhase.yml
  parameters:
    channel: preview

- job: ManifestPhase
  displayName: Create Manifest Lists

  dependsOn: 
   - stable
   - preview
  condition: succeeded()
  pool:
    name: PowerShell
    timeoutInMinutes: 30

  steps:
  - powershell: |  
       $dockerConfigFolder = "$env:userprofile/.docker"
       if(!(Test-Path $dockerConfigFolder)){ $null = new-item -Type Directory -Path $dockerConfigFolder}
       $dockerCliConfig = "$env:userprofile/.docker/config.json"
       $dockerCliBackup = "$env:userprofile/.docker/config-backup.json"
       if(Test-Path $dockerCliConfig) { copy-item $dockerCliConfig $dockerCliBackup -force}
       @{experimental='enabled'}|ConvertTo-Json | Out-File -Encoding ascii -FilePath $dockerCliConfig
        
    displayName: 'enable docker cli experimental features'

  - powershell: 'docker login $(dockerHost) -u $(dockerUserName) -p $(dockerKey)' 
    displayName: 'docker login'

  - powershell: |
      ./createAllManifests.ps1 -Registry $(dockerHost)/$(dockerNamespace)'
    displayName: 'Create Manifest Lists'

  - powershell: 'docker logout $(dockerHost)' 
    displayName: 'docker logout'
    condition: always()
