parameters:
  channel: 'preview'
  jobName: ''
  vmImage: 'ubuntu-latest'
  winCiParameter: '-CI -TagFilter 1809'
  acr: 'NoAcr'
  useacr: 'false'
  osFilter: 'All'

stages:
  - stage: GenerateYaml_${{ coalesce(parameters.jobName, parameters.channel) }}
    variables:
      jobName: ${{ coalesce(parameters.jobName, parameters.channel) }}
    dependsOn: []
    displayName: Build ${{ parameters.channel }}
    jobs:
    - job: GenerateYaml_${{ variables.jobName }}
      pool:
        vmImage: ubuntu-latest
      displayName: Generate Matrix YAML ${{ parameters.channel }}
      steps:
      - pwsh: |
          try {
             ./build.ps1 -GenerateMatrixJson -Channel ${{ parameters.channel }} -Verbose -Acr ${{ parameters.acr }} -OsFilter  ${{ parameters.osFilter }}
          } catch {
             Get-Error $_
             throw
          }
        displayName: Generate Matrix YAML
        condition: succeededOrFailed()
        name: matrix
      - pwsh: |
          dir env:matrix_* | out-string -Width 1000
        displayName: Capture Matrix YAML
        condition: succeededOrFailed()
    - template: phase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ variables.jobName }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_amd64']
        dependsOn: GenerateYaml_${{ variables.jobName }}
        jobName: Build_Linux_x64
        useacr: ${{ parameters.useacr }}
    - template: phase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ variables.jobName }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_arm64']
        dependsOn: GenerateYaml_${{ variables.jobName }}
        jobName: Build_Linux_ARM64
        useacr: ${{ parameters.useacr }}
        pool: PS-PowerShell-ARM
        vmImage: PSMMSUbuntu20.04-ARM64-secure
    - template: phase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ variables.jobName }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_arm32']
        dependsOn: GenerateYaml_${{ variables.jobName }}
        jobName: Build_Linux_ARM32
        useacr: ${{ parameters.useacr }}
        pool: PS-PowerShell-ARM
        vmImage: PSMMSUbuntu20.04-ARM64-secure
    - template: phase.yml
      parameters:
        matrix: dependencies.GenerateYaml_${{ variables.jobName }}.outputs['matrix.matrix_${{ parameters.channel }}_windows_amd64']
        dependsOn: GenerateYaml_${{ variables.jobName }}
        jobName: Build_Win_x64
        vmImage: windows-2022
        ciParameter: ${{ parameters.winCiParameter }}
        useacr: ${{ parameters.useacr }}
