name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

resources:
- repo: self
  clean: true

variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1

stages:
  - template: stage.yml
    parameters:
      channel: stable
      acr: OnlyAcr
      useacr: true
      winCiParameter: ''
  - template: stage.yml
    parameters:
      channel: preview
      acr: OnlyAcr
      useacr: true
      winCiParameter: ''
