name: Bug report 🐛
description: Report errors or unexpected behavior 🤔
labels: Needs-Triage
body:
## Check list

- [ ] Verified that this is not a [Known Issue](https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues)
- [ ] Verified this is not an issues in the underlying windows container that should be reported to [Windows Feedback Hub](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)

## Steps to reproduce
<!-- Please include any docker commands you used to run the image -->

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

<!-- provide the docker info -->

```sh
> docker info
```

<!-- provide the output of $PSVersionTable from powershell in the docker container -->

```powershell
> $PSVersionTable
```
