version: 1

# update_schedule: live is only supported on javascript, ruby:bundler, python, php:composer, dotnet:nuget, rust:cargo, elixir:hex

update_configs:
  - package_manager: "docker"
    directory: "/release/preview/alpine39/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/alpine311/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/centos8/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/debian10/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/debian11/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/fedora/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/nanoserver1809/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/ubuntu20.04/docker"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/windowsservercore/dependabot"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/release/preview/alpine38/dependabot"
    update_schedule: "weekly"
