parameters:
    - name: "channel"
      default: 'preview'
    - name: "vmImage"
      default: 'ubuntu-16.04'
    - name: "acr"
      default: 'All'
    - name: "useacr"
      default: 'false'
    - name: "osFilter"
      default: 'All'

stages:
    - stage: Release_${{ parameters.channel }}
      condition: succeededOrFailed()
      dependsOn: ['Approve_Release']
      displayName: Release ${{ parameters.channel }}
      jobs:
      - job: GenerateYaml_${{ parameters.channel }}
        pool:
            vmImage: ubuntu-16.04
        displayName: Generate Matrix YAML ${{ parameters.channel }}
        steps:
        - pwsh: |
            ./build.ps1 -GenerateMatrixJson -Channel ${{ parameters.channel }} -Verbose -Acr ${{ parameters.acr }} -OsFilter  ${{ parameters.osFilter }}
          displayName: Generate Matrix YAML
          condition: succeededOrFailed()
          name: matrix
        - pwsh: |
            dir env:matrix_* | out-string -Width 1000
          displayName: Capture Matrix YAML
          condition: succeededOrFailed()

      - template: ./releaseJob.yml
        parameters:
          jobName: ${{ parameters.channel }}_${{ parameters.osFilter }}
          matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_windows']
          dependsOn:
            - GenerateYaml_${{ parameters.channel }}

      - template: ./releaseJob.yml
        parameters:
          jobName: ${{ parameters.channel }}_linux
          matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux']
          dependsOn:
            - GenerateYaml_${{ parameters.channel }}
