parameters:
    - name: "channel"
      default: 'preview'
    - name: "vmImage"
      default: PSMMSUbuntu20.04-Secure
    - name: "acr"
      default: 'All'
    - name: "useacr"
      default: 'false'
    - name: "osFilter"
      default: 'All'
    - name: "WhatIf"
      default: 'No'


stages:
    - stage: Release_${{ parameters.channel }}
      condition: succeeded()
      dependsOn: ['Approve_Release']
      displayName: Release ${{ parameters.channel }}
      jobs:
      - job: GenerateYaml_${{ parameters.channel }}
        pool:
          name: PowerShell1ES
          demands:
            - ImageOverride -equals ${{ parameters.vmImage }}

        displayName: Generate Matrix YAML ${{ parameters.channel }}
        steps:

          - pwsh: |
              ./build.ps1 -GenerateMatrixJson -Channel ${{ parameters.channel }} -Verbose -Acr ${{ parameters.acr }} -OsFilter  ${{ parameters.osFilter }}
            displayName: Generate Matrix YAML
            condition: succeededOrFailed()
            name: matrix

          - pwsh: |
              dir env:matrix_* | out-string -Width 1000
            displayName: Capture Matrix YAML
            condition: succeededOrFailed()

      - template: ./releaseJob.yml
        parameters:
          jobName: ${{ parameters.channel }}_${{ parameters.osFilter }}_x64
          matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_windows_amd64']
          WhatIf: ${{ parameters.WhatIf }}
          vmImage: "PSMMS2019-Secure"
          dependsOn:
            - GenerateYaml_${{ parameters.channel }}

      - template: ./releaseJob.yml
        parameters:
          jobName: ${{ parameters.channel }}_linux_x64
          matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_amd64']
          WhatIf: ${{ parameters.WhatIf }}
          vmImage: "PSMMSUbuntu20.04-Secure"
          dependsOn:
            - GenerateYaml_${{ parameters.channel }}

      - template: ./releaseJob.yml
        parameters:
          jobName: ${{ parameters.channel }}_linux_arm64
          matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_arm64']
          WhatIf: ${{ parameters.WhatIf }}
          vmImage: "PSMMSUbuntu20.04-Secure"
          dependsOn:
            - GenerateYaml_${{ parameters.channel }}
            
      - template: ./releaseJob.yml
        parameters:
          jobName: ${{ parameters.channel }}_linux_arm32
          matrix: dependencies.GenerateYaml_${{ parameters.channel }}.outputs['matrix.matrix_${{ parameters.channel }}_linux_arm32']
          WhatIf: ${{ parameters.WhatIf }}
          vmImage: "PSMMSUbuntu20.04-Secure"
          dependsOn:
            - GenerateYaml_${{ parameters.channel }}

    - stage: Release_ManifestList_${{ parameters.channel }}
      jobs:
      - template: ./releaseManifestList.yml
        parameters:
          jobName: ${{ parameters.channel }}_manifest_list
          channel: ${{ parameters.channel }}
          WhatIf: ${{ parameters.WhatIf }}
