parameters:
    - name: "channel"
      default: 'preview'
    - name: "WhatIf"
      default: 'No'

stages:
- template: ./testStage.yml
  parameters:
    channel: ${{ parameters.channel }}

- template: ./releaseStage.yml
  parameters:
    channel: ${{ parameters.channel }}
    WhatIf: ${{ parameters.WhatIf }}
