name: 'Process reminders'

permissions:
  contents: read

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@e59091b4e9705a6108120cb50823108df35b5392 # v1.0.12
