# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Daily Updates

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    # At 20:20 UTC on every day-of-week from Monday through Friday.
    - cron:  '0 0/4 * * *'
defaults:
  run:
    shell: pwsh
env:
  UPDATE_SCRIPT_PATH: ./tools/updateScript.ps1
jobs:
  update-release-build-parameters:
    name: Update Release Build Parameters
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
      contents: write  # for peter-evans/create-pull-request to create branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto-update formula
        run: |
          &$env:UPDATE_SCRIPT_PATH -FormulaPath $env:FORMULA_PATH -Channel $env:CHANNEL_NAME
      - name: Create Pull Request
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: "${{ secrets.PR_PAT }}"
          commit-message: "Update the release build yaml with the latest versions"
          committer: PwshBot <pwshbot@microsoft.com>
          author: PwshBot <pwshbot@microsoft.com>
          title: "Update the release build yaml with the latest versions"
          base: master
          draft: false
          branch: update-release-build
          push-to-fork: pwshBot/PowerShell-Docker
  update-matrix-json:
    name: Update Matrix Json
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
      contents: write  # for peter-evans/create-pull-request to create branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Auto-update Matrix JSON
        run: |
          ./tools/updateJson.ps1

      - name: Create Pull Request
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: "${{ secrets.PR_PAT }}"
          commit-message: "Update the matrix json"
          committer: PwshBot <pwshbot@microsoft.com>
          author: PwshBot <pwshbot@microsoft.com>
          title: "Update the matrix json"
          base: master
          draft: false
          branch: update-matrix-json
          push-to-fork: pwshBot/PowerShell-Docker
